apiVersion: v1
kind: Service
metadata:
  name: {{ include "transfer-sh.fullname" . }}
  labels:
    {{- include "transfer-sh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transfer-sh.selectorLabels" . | nindent 4 }}
