apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak-server.fullname" . }}
  labels:
    {{- include "teamspeak-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.voice.port }}
      targetPort: voice
      protocol: UDP
      name: voice
    - port: {{ .Values.service.filetransfer.port }}
      targetPort: filetransfer
      protocol: TCP
      name: filetransfer
    - port: {{ .Values.service.serverquery.port }}
      targetPort: serverquery
      protocol: TCP
      name: serverquery
  selector:
    {{- include "teamspeak-server.selectorLabels" . | nindent 4 }}
